### PR TITLE
disable Fortran in cmake

### PR DESCRIPTION
**Pull request by Thomas-Ulrich**
I will also update the spack packages.
(I had to install seissol-env in a cluster without ifort).

### CODE REVIEW

**Comment by davschneller** [comment]
FORTRAN does only seem to be needed when tests are enabled—maybe move it in there, or remove FORTRAN testing alltogether (I'd guess it's this line here only https://github.com/SeisSol/easi/pull/43/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR212 )

**Comment by Thomas-Ulrich** [comment]
So you suggest moving the line remove within:
if (TESTING)
?

**Comment by davschneller** [comment]
Yup, we can do that; or also remove the testing with `special.f90`

**Comment by Thomas-Ulrich** [comment]
done

**Review by davschneller — APPROVED** [review]

**Pull request merged**
